#!/bin/bash
# Claude Code PreCompact hook: Checkpoint agent state to bean file
# Fail-open: all errors exit 0 silently.

main() {
    local PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
    cd "$PROJECT_DIR" || return

    cat > /dev/null

    local BRANCH
    BRANCH=$(git branch --show-current 2>/dev/null) || return

    if [ -z "$BRANCH" ] || [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
        return
    fi

    local BEAN_ID=""
    if [[ "$BRANCH" =~ ^[a-z]+/(agentbox-[a-zA-Z0-9]+)-.* ]]; then
        BEAN_ID="${BASH_REMATCH[1]}"
    elif [[ "$BRANCH" =~ ^[a-z]+/(beans-[a-zA-Z0-9]+)-.* ]]; then
        BEAN_ID="${BASH_REMATCH[1]}"
    fi

    if [ -z "$BEAN_ID" ]; then
        return
    fi

    local HEAD_SHA HEAD_MSG DIFF_STAT CACHED_STAT RECENT_COMMITS
    HEAD_SHA=$(git rev-parse --short HEAD 2>/dev/null) || HEAD_SHA="unknown"
    HEAD_MSG=$(git log --oneline -1 2>/dev/null) || HEAD_MSG="unknown"
    DIFF_STAT=$(git diff --stat 2>/dev/null) || DIFF_STAT=""
    CACHED_STAT=$(git diff --cached --stat 2>/dev/null) || CACHED_STAT=""
    RECENT_COMMITS=$(git log --oneline -5 2>/dev/null) || RECENT_COMMITS=""

    local BEAN_JSON BEAN_BODY TOTAL_ITEMS CHECKED_ITEMS
    BEAN_JSON=$(timeout 2s beans query "{ bean(id: \"${BEAN_ID}\") { body } }" --json 2>/dev/null) || BEAN_JSON=""

    if [ -n "$BEAN_JSON" ]; then
        BEAN_BODY=$(echo "$BEAN_JSON" | jq -r '.bean.body // empty' 2>/dev/null) || BEAN_BODY=""
    fi

    TOTAL_ITEMS=$(printf '%b' "$BEAN_BODY" | grep -c '^\- \[[ x]\]' 2>/dev/null || echo "0")
    CHECKED_ITEMS=$(printf '%b' "$BEAN_BODY" | grep -c '^\- \[x\]' 2>/dev/null || echo "0")

    local TREE_STATUS STAGE_STATUS
    if [ -z "$DIFF_STAT" ]; then
        TREE_STATUS="clean"
    else
        TREE_STATUS=$(echo "$DIFF_STAT" | tail -1)
    fi
    if [ -z "$CACHED_STAT" ]; then
        STAGE_STATUS="clean"
    else
        STAGE_STATUS=$(echo "$CACHED_STAT" | tail -1)
    fi

    local TIMESTAMP
    TIMESTAMP=$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null || echo "unknown")

    local CHECKPOINT
    CHECKPOINT="## Agent Checkpoint

*Auto-generated by PreCompact hook at ${TIMESTAMP}. Do not edit manually.*

- **Branch**: ${BRANCH}
- **HEAD**: ${HEAD_SHA} -- ${HEAD_MSG}
- **Checklist progress**: ${CHECKED_ITEMS}/${TOTAL_ITEMS} items completed
- **Working tree**: ${TREE_STATUS}
- **Staging area**: ${STAGE_STATUS}

### Recent commits (newest first)

\`\`\`
${RECENT_COMMITS}
\`\`\`"

    local BEAN_PATH_JSON BEAN_FILENAME BEANS_BASE_DIR BEAN_FILE_PATH
    BEAN_PATH_JSON=$(timeout 2s beans query "{ bean(id: \"${BEAN_ID}\") { path } }" --json 2>/dev/null) || BEAN_PATH_JSON=""

    if [ -n "$BEAN_PATH_JSON" ]; then
        BEAN_FILENAME=$(echo "$BEAN_PATH_JSON" | jq -r '.bean.path // empty' 2>/dev/null) || BEAN_FILENAME=""
    fi

    if [ -n "$BEAN_FILENAME" ]; then
        BEANS_BASE_DIR="${BEANS_DIR:-${PROJECT_DIR}/.beans}"
        BEAN_FILE_PATH="${BEANS_BASE_DIR}/${BEAN_FILENAME}"

        if [ -f "$BEAN_FILE_PATH" ]; then
            local TEMP_FILE
            TEMP_FILE=$(mktemp)

            awk -v checkpoint="$CHECKPOINT" '
            BEGIN { in_checkpoint = 0; in_code_block = 0; checkpoint_written = 0; has_dod = 0 }
            /^```/ { if (in_code_block) { in_code_block = 0 } else { in_code_block = 1 } }
            !in_code_block && /^## Agent Checkpoint/ { in_checkpoint = 1; next }
            in_checkpoint && !in_code_block && /^## / { print checkpoint; print ""; checkpoint_written = 1; in_checkpoint = 0; print; next }
            in_checkpoint { next }
            !in_code_block && /^## Definition of Done/ { if (!checkpoint_written) { print checkpoint; print ""; checkpoint_written = 1 }; has_dod = 1 }
            { print }
            END { if (in_checkpoint && !checkpoint_written) { print checkpoint; checkpoint_written = 1 }; if (!checkpoint_written) { print ""; print checkpoint } }
            ' "$BEAN_FILE_PATH" > "$TEMP_FILE"

            mv "$TEMP_FILE" "$BEAN_FILE_PATH"
        fi
    fi

    echo "$CHECKPOINT"
}

main "$@" || true
exit 0
