#!/usr/bin/env bash
# Sync Codex CLI settings into the container.
# Copies the template settings on first run; skips if config already exists
# to preserve any user customizations.
# Generated by agentbox -- do not edit manually.
#
# NOTE: This script requires devcontainer.json wiring (postStartCommand and
# volume mount for ~/.codex) to be effective. That integration is tracked in
# bean agentbox-0w8k.
set -euo pipefail

TEMPLATE="/workspace/.devcontainer/codex-config.toml"
SETTINGS_DIR="$HOME/.codex"
SETTINGS_FILE="$SETTINGS_DIR/config.toml"

if [ ! -f "$TEMPLATE" ]; then
    echo "Warning: Codex settings template not found at $TEMPLATE" >&2
    exit 0
fi

# Volume mounts may be created with root ownership; fix before writing.
sudo chown -R "$(id -u):$(id -g)" "$SETTINGS_DIR" 2>/dev/null || true
mkdir -p "$SETTINGS_DIR"

if [ ! -f "$SETTINGS_FILE" ]; then
    cp "$TEMPLATE" "$SETTINGS_FILE"
fi
