#!/usr/bin/env bash
# Sync Claude Code user settings into the container.
# Copies the template settings on first run; deep-merges on subsequent runs
# so that runtime state written by Claude Code is preserved.
# Generated by ccbox -- do not edit manually.
set -euo pipefail

TEMPLATE="/workspace/.devcontainer/claude-user-settings.json"
SETTINGS_DIR="$HOME/.claude"
SETTINGS_FILE="$SETTINGS_DIR/settings.json"

if [ ! -f "$TEMPLATE" ]; then
    echo "Warning: Claude settings template not found at $TEMPLATE" >&2
    exit 0
fi

# Volume mounts may be created with root ownership; fix before writing.
sudo chown -R "$(id -u):$(id -g)" "$SETTINGS_DIR" 2>/dev/null || true
mkdir -p "$SETTINGS_DIR"

if [ ! -f "$SETTINGS_FILE" ]; then
    cp "$TEMPLATE" "$SETTINGS_FILE"
else
    # Deep-merge: existing settings as base, template wins on conflicts.
    TMPFILE="$(mktemp)"
    trap 'rm -f "$TMPFILE"' EXIT
    jq -s '.[0] * .[1]' "$SETTINGS_FILE" "$TEMPLATE" > "$TMPFILE"
    mv "$TMPFILE" "$SETTINGS_FILE"
    trap - EXIT
fi
