#!/usr/bin/env bash
set -euo pipefail

# warmup-dns.sh -- Pre-resolve dynamic domains through local dnsmasq.
#
# Reads dynamic-domains.conf and resolves each domain via dig through
# the local dnsmasq instance (127.0.0.1). This triggers dnsmasq's ipset
# integration, populating the allowed_ips set so that dynamic domain IPs
# are available before the user needs network access.
#
# Generated by agentbox -- do not edit manually.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="${SCRIPT_DIR}/dynamic-domains.conf"

if [[ ! -f "${CONF_FILE}" ]]; then
    echo "[warmup-dns] WARNING: ${CONF_FILE} not found, skipping DNS warmup."
    exit 0
fi

echo "[warmup-dns] Warming up DNS for dynamic domains..."

while IFS= read -r line; do
    # Strip comments and whitespace.
    domain="$(echo "${line}" | awk '{print $1}')"

    # Skip blank lines and comment-only lines.
    if [[ -z "${domain}" ]] || [[ "${domain}" == \#* ]]; then
        continue
    fi

    echo "[warmup-dns] Resolving ${domain}..."
    dig +short "${domain}" @127.0.0.1 > /dev/null 2>&1 || true
done < "${CONF_FILE}"

echo "[warmup-dns] DNS warmup complete."
