package render

import (
	"bytes"
	"strings"
	"testing"

	"github.com/bjro/agentbox/internal/stack"
)

// --- Integration tests (through Merge + RenderCodex) ---

func TestRenderCodex_NoError(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go, stack.Node}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	if len(files.Config) == 0 {
		t.Error("Config is empty")
	}
	if len(files.SyncSettings) == 0 {
		t.Error("SyncSettings is empty")
	}
}

func TestRenderCodex_Config_ValidTOML(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go, stack.Node}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	output := string(files.Config)
	for _, key := range []string{"approval_policy", "sandbox_mode"} {
		if !strings.Contains(output, key) {
			t.Errorf("Config missing expected TOML key %q", key)
		}
	}
}

func TestRenderCodex_Config_SpecificValues(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go, stack.Node}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	output := string(files.Config)
	for _, expected := range []string{
		`approval_policy = "unless-allow-listed"`,
		`sandbox_mode = "danger-full-access"`,
	} {
		if !strings.Contains(output, expected) {
			t.Errorf("Config missing expected value %q", expected)
		}
	}
}

func TestRenderCodex_Config_GeneratedComment(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	if !strings.Contains(string(files.Config), "Generated by agentbox") {
		t.Error("Config missing 'Generated by agentbox' comment")
	}
}

// --- Sync script tests ---

func TestRenderCodex_SyncSettings_ScriptStructure(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	output := string(files.SyncSettings)

	checks := []string{
		"#!/usr/bin/env bash",
		"set -euo pipefail",
		"codex-config.toml",
		"$HOME/.codex",
		"config.toml",
	}
	for _, check := range checks {
		if !strings.Contains(output, check) {
			t.Errorf("SyncSettings missing structural marker %q", check)
		}
	}
}

func TestRenderCodex_SyncSettings_CopyOnFirstRunSkipIfExists(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	output := string(files.SyncSettings)

	// Should use copy-on-first-run/skip-if-exists, not deep merge.
	if !strings.Contains(output, `[ ! -f "$SETTINGS_FILE" ]`) {
		t.Error("SyncSettings should contain first-run conditional check")
	}
	if strings.Contains(output, "jq") {
		t.Error("SyncSettings should NOT contain jq (no deep merge for TOML)")
	}
}

// --- Static template verification ---

func TestRenderCodex_Config_IsStatic(t *testing.T) {
	cfgGo, err := Merge([]stack.StackID{stack.Go}, nil)
	if err != nil {
		t.Fatalf("Merge (Go): %v", err)
	}

	allIDs := []stack.StackID{stack.Go, stack.Node, stack.Python, stack.Rust, stack.Ruby}
	cfgAll, err := Merge(allIDs, nil)
	if err != nil {
		t.Fatalf("Merge (all): %v", err)
	}

	filesGo, err := RenderCodex(cfgGo)
	if err != nil {
		t.Fatalf("RenderCodex (Go): %v", err)
	}

	filesAll, err := RenderCodex(cfgAll)
	if err != nil {
		t.Fatalf("RenderCodex (all): %v", err)
	}

	if !bytes.Equal(filesGo.Config, filesAll.Config) {
		t.Error("Config output differs between Go-only and all-stacks configs; it should be static")
	}
}

func TestRenderCodex_SyncSettings_IsStatic(t *testing.T) {
	cfgGo, err := Merge([]stack.StackID{stack.Go}, nil)
	if err != nil {
		t.Fatalf("Merge (Go): %v", err)
	}

	allIDs := []stack.StackID{stack.Go, stack.Node, stack.Python, stack.Rust, stack.Ruby}
	cfgAll, err := Merge(allIDs, nil)
	if err != nil {
		t.Fatalf("Merge (all): %v", err)
	}

	filesGo, err := RenderCodex(cfgGo)
	if err != nil {
		t.Fatalf("RenderCodex (Go): %v", err)
	}

	filesAll, err := RenderCodex(cfgAll)
	if err != nil {
		t.Fatalf("RenderCodex (all): %v", err)
	}

	if !bytes.Equal(filesGo.SyncSettings, filesAll.SyncSettings) {
		t.Error("SyncSettings output differs between Go-only and all-stacks configs; it should be static")
	}
}

// --- Template artifact tests ---

func TestRenderCodex_Config_NoTemplateArtifacts(t *testing.T) {
	allIDs := []stack.StackID{stack.Go, stack.Node, stack.Python, stack.Rust, stack.Ruby}
	cfg, err := Merge(allIDs, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	for _, artifact := range []string{"<no value>", "<nil>", "{{", "}}"} {
		if bytes.Contains(files.Config, []byte(artifact)) {
			t.Errorf("Config contains template artifact %q", artifact)
		}
	}
}

func TestRenderCodex_SyncSettings_NoTemplateArtifacts(t *testing.T) {
	allIDs := []stack.StackID{stack.Go, stack.Node, stack.Python, stack.Rust, stack.Ruby}
	cfg, err := Merge(allIDs, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	for _, artifact := range []string{"<no value>", "<nil>", "{{", "}}"} {
		if bytes.Contains(files.SyncSettings, []byte(artifact)) {
			t.Errorf("SyncSettings contains template artifact %q", artifact)
		}
	}
}

// --- Determinism ---

func TestRenderCodex_Config_Deterministic(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go, stack.Node, stack.Python}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files1, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex (1): %v", err)
	}

	files2, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex (2): %v", err)
	}

	if !bytes.Equal(files1.Config, files2.Config) {
		t.Error("Config output is not deterministic across two renders")
	}
}

func TestRenderCodex_SyncSettings_Deterministic(t *testing.T) {
	cfg, err := Merge([]stack.StackID{stack.Go, stack.Node, stack.Python}, nil)
	if err != nil {
		t.Fatalf("Merge: %v", err)
	}

	files1, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex (1): %v", err)
	}

	files2, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex (2): %v", err)
	}

	if !bytes.Equal(files1.SyncSettings, files2.SyncSettings) {
		t.Error("SyncSettings output is not deterministic across two renders")
	}
}

// --- Isolation tests (hand-built GenerationConfig) ---

func TestRenderCodex_DirectConfig_EmptyConfig(t *testing.T) {
	cfg := GenerationConfig{}

	files, err := RenderCodex(cfg)
	if err != nil {
		t.Fatalf("RenderCodex: %v", err)
	}

	if len(files.Config) == 0 {
		t.Error("Config is empty for zero-value GenerationConfig")
	}
	if len(files.SyncSettings) == 0 {
		t.Error("SyncSettings is empty for zero-value GenerationConfig")
	}

	// Static templates should produce valid output even with empty config.
	if !strings.Contains(string(files.Config), "approval_policy") {
		t.Error("Config should contain approval_policy even with empty config")
	}
}
